spring:
  profiles:
    active: dev
    
server:  
  port: 8080  #配置端口
  session-timeout: 30  
  tomcat.max-threads: 5  
  tomcat.uri-encoding: UTF-8  
  
# spring:  
#   datasource:  #数据库配置
#     url : jdbc:mysql://localhost:3306/newbirds  
#     username : root  
#     password : mymysql  
#     driverClassName : com.mysql.jdbc.Driver
    

